--
-- PostgreSQL database dump
--

\restrict VWNd0gqWAuAQxdoGPDGMIit52ra333zkUbpM05XjYQFMJgQEqMDTfc5cBf427Wx

-- Dumped from database version 15.19
-- Dumped by pg_dump version 17.11 (Ubuntu 17.11-1.pgdg26.04+2)

-- Started on 2026-09-11 00:59:13 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16399)
-- Name: courses; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.courses OWNER TO "user";

--
-- TOC entry 216 (class 1259 OID 16398)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16405)
-- Name: grades; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.grades (
    id bigint NOT NULL,
    student_id bigint,
    courses_id bigint,
    score smallint NOT NULL,
    CONSTRAINT grades_score_check CHECK (((score >= 0) AND (score <= 100)))
);


ALTER TABLE public.grades OWNER TO "user";

--
-- TOC entry 218 (class 1259 OID 16404)
-- Name: grades_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.grades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16391)
-- Name: students; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL
);


ALTER TABLE public.students OWNER TO "user";

--
-- TOC entry 214 (class 1259 OID 16390)
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3313 (class 2606 OID 16403)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 3315 (class 2606 OID 16410)
-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (id);


--
-- TOC entry 3309 (class 2606 OID 16397)
-- Name: students students_email_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_email_key UNIQUE (email);


--
-- TOC entry 3311 (class 2606 OID 16395)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 3316 (class 2606 OID 16416)
-- Name: grades grades_courses_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_courses_id_fkey FOREIGN KEY (courses_id) REFERENCES public.courses(id);


--
-- TOC entry 3317 (class 2606 OID 16411)
-- Name: grades grades_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


-- Completed on 2026-09-11 00:59:13 MSK

--
-- PostgreSQL database dump complete
--

\unrestrict VWNd0gqWAuAQxdoGPDGMIit52ra333zkUbpM05XjYQFMJgQEqMDTfc5cBf427Wx

